# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# Set mandatory reviewers
reviewers:
 - f1lem0n
 - konsternacja