name: pr-label

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:

  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.4.3
        env:
          FALSCIFY_BOT_TOKEN: "${{ secrets.FALSCIFY_BOT_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "25": "S",
              "150": "M",
              "500": "L",
              "1000": "XL"
            }

  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: "${{ secrets.FALSCIFY_BOT_TOKEN }}"
          title-regex: "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore): .{1,}"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: true
          on-failed-regex-comment:
            "Please stick to Conventional Commits syntax for PR titles ;)"
          on-succeeded-regex-dismiss-review-comment:
            "Thank you <3"
