name: stale PRs

on:
  schedule:
    - cron: 0 0 * * *

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: actions/stale@v7
        uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'There has been no activity in here for 7 days... You now have 1 more week before this PR is automatically closed.'
          close-pr-message: 'This PR was closed because it has been marked as stale for 7 days. Better luck next time!'
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-pr-stale: 7
          days-before-pr-close: 6 # set to x-1 to actually count x days (include day 0 w/ "stale" comment)
          stale-pr-label: stale
          exempt-draft-pr: true
